---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: {{ .Values.nodedrainer.name | quote }}
  name: {{ .Values.nodedrainer.name | quote }}
  namespace: {{ .Values.nodedrainer.namespace | quote }}